=head1 NAME

PTroller - Merge several images into a single one


=head1 SYNOPSIS

B<PTroller> [options] I<tiff_file(s)>


=head1 DESCRIPTION

B<PTroller> takes a set of images and merges them into a single one.


=head1 OPTIONS

=over

=item B<-o> I<filename>

Output filename (defaults to I<merged.tif>).

=item B<-f>

Force processing (do not stop on warnings).

=item B<-x>

Delete source files (use with care).

=item B<-q>

Quiet run

=item B<-h>

Show this message

=back


=head1 AUTHORS

Panorama Tools was originally created by Professor Helmut Dersch, it's
now maintained by Bruno Postle <bruno@postle.net>.

PTroller was written by Daniel M German <dmgerman@uvic.ca>.

This manpage was written by Cyril Brulebois
<cyril.brulebois@enst-bretagne.fr> and is licensed under the same
terms as the libpano13 package itself.
